### ISSUE TITLE
Crash with CoFH

### ISSUE THREAD

**Issue by Ushupiuck** [MiningMark48/MiningLib#1]
As the crash log below states, you're using the old API, and it needs to be updated.
[crash-2017-07-26_19.20.37-client.txt](https://github.com/MiningMark48/MiningLib/files/1178262/crash-2017-07-26_19.20.37-client.txt)
thanks for reading, and have a good day! ^w^

**Comment by MiningMark48** [comment]
Will fix and have a version available soon! Thanks for the alert.

**Comment by MiningMark48** [comment]
Fixed in ~~upcoming~~ [this](https://minecraft.curseforge.com/projects/mininglib/files/2456482) release.

**Comment by Ushupiuck** [comment]
thanks!
